version: 1.1.{build}
image: Visual Studio 2019
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  marketplacepublishtoken:
    secure: JYg/B7OanltuZBh0LcLnAnWacGboU3C5s0asiIANkwYxHXYA5+XFcD8v7Ji/dsHZP49lpgSvYUSDYxAztpHtFw==
  matrix:
  - {}
before_build:
- ps: >-
    nuget restore

    .\tools\update-vsixversion.ps1 $($env:appveyor_build_version)
build:
  project: Telia.GraphQL.sln
  publish_nuget: true
  publish_nuget_symbols: false
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: jybNeBQRLT8IpnQQiYJGG2ay9ZFONaHOqQ5qSmPhYgbjGOLo7QKXCvlaTPty83Yl
  on:
    branch: master
after_deploy:
- ps: .\tools\publish-vsix.ps1